sonar.projectKey=MalavikaAK_DEVOPS_FOREX
sonar.organization=malavikaak

sonar.projectName=DEVOPS_FOREX – Production DevOps Pipeline
sonar.projectVersion=3.0

# Source roots – Python backend and JS frontend
sonar.sources=backend,frontend/src

# Python settings
sonar.python.version=3.10

# Exclusions (don't scan node_modules, venv, tests for coverage)
sonar.exclusions=**/node_modules/**,**/__pycache__/**,**/dist/**,**/.venv/**

# Test paths
sonar.tests=backend
sonar.test.inclusions=**/test_*.py,**/*_test.py
